# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  toc_levels: 1..6  # 允许生成目录的标题级别

# SEO settings
title: Ayakouji
description: Your site description here
url: https://aquagull.github.io/Ayakouji

# Pagination
paginate: 5  # 每页显示的文章数量

# Customization
show_date: true      # 显示文章日期
show_categories: true # 显示文章分类

# Social links
social_links:
  - icon: "fa-github"
    url: "https://github.com/aquagull"

# Categories
categories:
  - category1
  - category2
