theme: minima
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  toc_levels: 1..6  # 允许生成目录的标题级别
